/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class CloudText {
    constructor() {
        this.Id = undefined;
        this.context = undefined;
    }

    setId(Id) {
        this.Id = Id;
    }

    getId() {
        return this.Id;
    }

    setContext(context) {
        this.context = context;
    }

    getContext() {
        return this.context;
    }
}

CloudText.className = 'CloudText';

export {CloudText}