/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class BookInfo {
    constructor() {
        this.id = undefined;
        this.bookName = undefined;
        this.author = undefined;
        this.price = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setBookName(bookName) {
        this.bookName = bookName;
    }

    getBookName() {
        return this.bookName;
    }

    setAuthor(author) {
        this.author = author;
    }

    getAuthor() {
        return this.author;
    }

    setPrice(price) {
        this.price = price;
    }

    getPrice() {
        return this.price;
    }
}

BookInfo.className = 'BookInfo';

export {BookInfo}